name: start-aws-services

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *' # 毎日AM 8:30に実行(+9:00)

jobs:
  #start-ec2:
  #  runs-on: ubuntu-latest
  #  permissions:
  #    id-token: write
  #    contents: read
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: configure aws credentials
  #    uses: aws-actions/configure-aws-credentials@v1-node16
  #    with:
  #      role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
  #      aws-region: ap-northeast-1
  #  - name: Start EC2 Instance
  #    run: sh ./scripts/ec2_start.sh
  start-ecs-item-service:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
        aws-region: ap-northeast-1
    - name: Start ECS Service
      run: sh ./scripts/ecs_start.sh item-service
  start-ecs-reservation-service:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
        aws-region: ap-northeast-1
    - name: Start ECS Service
      run: sh ./scripts/ecs_start.sh reservation-service
  start-ecs-user-service:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
        aws-region: ap-northeast-1
    - name: Start ECS Service
      run: sh ./scripts/ecs_start.sh user-service
