name: verify-parent-job

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/checkout@v3
    - name: execute verify
      run: mvn -B -Pcli verify
