name: verify-app-job

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # install msa-rms-parent for execution prepare
    - name: prepare execution - checkout msa-rms-parent
      uses: actions/checkout@v3
      with:
        repository: extact-io/msa-rms-parent
        path: msa-rms-parent
    - name: prepare execution - install msa-rms-parent
      run: mvn -B -Pcli install -DskipTests=true
      working-directory: msa-rms-parent
    
    # install msa-rms-platform for execution prepare
    - name: prepare execution - checkout msa-rms-platform
      uses: actions/checkout@v3
      with:
        repository: extact-io/msa-rms-platform
        path: msa-rms-platform
    - name: prepare execution - install msa-rms-platform
      run: mvn -B -Pcli install -DskipTests=true
      working-directory: msa-rms-platform
    
    # execute verify to target app
    - name: checkout target app
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        path: target-app
    - name: execute verify
      run: mvn -B -Pcli verify
      working-directory: target-app
